In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
%matplotlib inline
import seaborn as sns
from sklearn.utils import shuffle

In [88]:
#Load train and test datasets and shuffle the data 
train = shuffle(pd.read_csv("../Human_Activity_Recognition/human-activity-recognition-with-smartphones/train.csv"))
test = shuffle(pd.read_csv("../Human_Activity_Recognition/human-activity-recognition-with-smartphones/test.csv"))


tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
2726           0.272946          -0.026206          -0.097924   
4490           0.271550          -0.010033          -0.104589   
3110           0.276674          -0.017101          -0.106707   
5995           0.291316          -0.001065          -0.072461   
3686           0.276414          -0.018260          -0.106016   

      tBodyAcc-std()-X  tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  \
2726         -0.991364         -0.943502         -0.982904         -0.992612   
4490         -0.015317          0.090323         -0.279122         -0.033019   
3110         -0.996087         -0.994709         -0.984658         -0.996586   
5995         -0.336609         -0.279162         -0.303323         -0.381421   
3686         -0.991494         -0.983043         -0.994530         -0.992532   

      tBodyAcc-mad()-Y  tBodyAcc-mad()-Z  tBodyAcc-max()-X    ...     \
2726         -0.940185         -0.983258         -0.926985    ...      
4490         -0.063419         -0.324204         -0.008328    ...      
3110         -0.994575         -0.983022         -0.941940    ...      
5995         -0.253026         -0.337381          0.074430    ...      
3686         -0.987565         -0.994456         -0.936281    ...      

      fBodyBodyGyroJerkMag-kurtosis()  angle(tBodyAccMean,gravity)  \
2726                        -0.774672                     0.001787   
4490                         0.138324                     0.314252   
3110                        -0.468672                     0.039139   
5995                        -0.698254                    -0.044663   
3686                        -0.887039                     0.037702   

      angle(tBodyAccJerkMean),gravityMean)  angle(tBodyGyroMean,gravityMean)  \
2726                             -0.000998                          0.701185   
4490                              0.233292                          0.884944   
3110                             -0.072564                         -0.041340   
5995                             -0.551806                         -0.680774   
3686                             -0.602658                          0.040593   

      angle(tBodyGyroJerkMean,gravityMean)  angle(X,gravityMean)  \
2726                             -0.759881             -0.812518   
4490                              0.323620             -0.767534   
3110                              0.521934             -0.675011   
5995                              0.161405             -0.857202   
3686                             -0.489430              0.591757   

      angle(Y,gravityMean)  angle(Z,gravityMean)  subject  Activity  
2726              0.225955             -0.004362       15  STANDING  
4490              0.247209             -0.043840       22   WALKING  
3110              0.195767             -0.192074       16   SITTING  
5995              0.192929              0.046716       27   WALKING  
3686             -0.576933             -0.427187       19    LAYING  

[5 rows x 563 columns]

In [87]:
# Summary statistics of training and test data to check for missing values
print("Any missing sample in training set:",train.isnull().values.any())
print("Any missing sample in test set:",test.isnull().values.any(), "\n")

#Frequency distribution of classes"
train_outcome = pd.crosstab(index=train["Activity"],  # Make a crosstab
                              columns="count")      # Name the count column

train_outcome


Any missing sample in training set: False
Any missing sample in test set: False 



col_0               count
Activity                 
LAYING               1407
SITTING              1286
STANDING             1374
WALKING              1226
WALKING_DOWNSTAIRS    986
WALKING_UPSTAIRS     1073

In [109]:
# Seperating Predictors and Outcome values from train and test sets
X_train = pd.DataFrame(train.drop(['Activity','subject'],axis=1))
Y_train = train.Activity.values.astype(object)
X_test = pd.DataFrame(test.drop(['Activity','subject'],axis=1))
Y_test = test.Activity.values.astype(object)

# Dimension of Train and Test set 
print("Dimension of Train set",X_train.shape)
print("Dimension of Test set",X_test.shape,"\n")

# Transforming non numerical labels into numerical labels
from sklearn import preprocessing
encoder = preprocessing.LabelEncoder()

# encoding train labels 
encoder.fit(Y_train)
Y_train_label = encoder.transform(Y_train)

# encoding test labels 
encoder.fit(Y_test)
Y_test_label = encoder.transform(Y_test)

#Total Number of Continous and Categorical features in the training set
num_cols = X_train._get_numeric_data().columns
print("Number of numeric features:",num_cols.size)
#list(set(X_train.columns) - set(num_cols))


names_of_predictors = list(X_train.columns.values)



Dimension of Train set (7352, 561)
Dimension of Test set (2947, 561) 

Number of numeric features: 561


In [112]:
# Computing correlation matrix of predictors set to determine highly correlated variables 
train_corr = X_train.corr()

### Plotting Correlation Matrix 
# Generate a mask for the upper triangle
#mask = np.zeros_like(train_corr, dtype=np.bool)
#mask[np.triu_indices_from(mask)] = True

# Set up the matplotlib figure
#f, ax = plt.subplots(figsize=(11, 9))

# Generate a custom diverging colormap
#cmap = sns.diverging_palette(220, 10, as_cmap=True)

# Draw the heatmap with the mask and correct aspect ratio
#sns.heatmap(train_corr, mask=mask, cmap=cmap, vmax=.3, center=0,
#            square=True, linewidths=.5, cbar_kws={"shrink": .5})


# List of Highly correlated features in the dataset
corr_pred = train_corr.unstack()
high_corr_pred= corr_pred.sort_values(kind="quicksort")
high_corr_pred

tGravityAcc-arCoeff()-Z,2       tGravityAcc-arCoeff()-Z,1        -0.995297
tGravityAcc-arCoeff()-Z,1       tGravityAcc-arCoeff()-Z,2        -0.995297
angle(Z,gravityMean)            tGravityAcc-mean()-Z             -0.995070
tGravityAcc-mean()-Z            angle(Z,gravityMean)             -0.995070
tGravityAcc-arCoeff()-Z,2       tGravityAcc-arCoeff()-Z,3        -0.994684
tGravityAcc-arCoeff()-Z,3       tGravityAcc-arCoeff()-Z,2        -0.994684
tGravityAcc-arCoeff()-Z,4       tGravityAcc-arCoeff()-Z,3        -0.994256
tGravityAcc-arCoeff()-Z,3       tGravityAcc-arCoeff()-Z,4        -0.994256
angle(Y,gravityMean)            tGravityAcc-mean()-Y             -0.993502
tGravityAcc-mean()-Y            angle(Y,gravityMean)             -0.993502
angle(Z,gravityMean)            tGravityAcc-max()-Z              -0.992869
tGravityAcc-max()-Z             angle(Z,gravityMean)             -0.992869
tGravityAcc-arCoeff()-Y,1       tGravityAcc-arCoeff()-Y,2        -0.991898
tGravityAcc-arCoeff()-Y,2

In [121]:
# Scaling the Train and Test feature set 
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [170]:
#Libraries to Build Ensemble Model : Random Forest Classifier 
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import cross_val_score, GridSearchCV

# Create the parameter grid based on the results of random search 
param_grid = {
    'bootstrap': [True],
    'max_features': ['auto', 'sqrt'],
    'n_estimators': [100, 200, 300,500]
}
# Create a based model
rf_classifier = RandomForestClassifier()

# Instantiate the grid search model
grid_search = GridSearchCV(estimator = rf_classifier, param_grid = param_grid, 
                          cv = 3, n_jobs = -1, verbose = 2)

# Fitting Random Forest Classification to the Training set
#rf_classifier.fit(X_train_scaled, Y_train_label)


In [171]:
# Fit the grid search to the data
grid_search.fit(X_train_scaled, Y_train_label)


Fitting 3 folds for each of 8 candidates, totalling 24 fits
[CV] bootstrap=True, max_features=auto, n_estimators=100 .............
[CV] bootstrap=True, max_features=auto, n_estimators=100 .............
[CV] bootstrap=True, max_features=auto, n_estimators=100 .............
[CV] bootstrap=True, max_features=auto, n_estimators=200 .............
[CV] bootstrap=True, max_features=auto, n_estimators=200 .............
[CV] bootstrap=True, max_features=auto, n_estimators=200 .............
[CV] bootstrap=True, max_features=auto, n_estimators=300 .............
[CV] bootstrap=True, max_features=auto, n_estimators=300 .............
[CV]  bootstrap=True, max_features=auto, n_estimators=100, total=   9.5s
[CV] bootstrap=True, max_features=auto, n_estimators=300 .............
[CV]  bootstrap=True, max_features=auto, n_estimators=100, total=   9.7s
[CV] bootstrap=True, max_features=auto, n_estimators=500 .............
[CV]  bootstrap=True, max_features=auto, n_estimators=100, total=   9.8s
[CV] bootst

[Parallel(n_jobs=-1)]: Done  22 out of  24 | elapsed:  1.6min remaining:    8.8s


[CV]  bootstrap=True, max_features=sqrt, n_estimators=500, total=  37.1s


[Parallel(n_jobs=-1)]: Done  24 out of  24 | elapsed:  1.7min finished


GridSearchCV(cv=3, error_score='raise',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
       fit_params=None, iid=True, n_jobs=-1,
       param_grid={'bootstrap': [True], 'max_features': ['auto', 'sqrt'], 'n_estimators': [100, 200, 300, 500]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=2)

 ##### Performance evaluation of the trained model consists of following steps:

 -> Predicting the acticity class of the test data using test feature set (X_test). 

 -> Evaluating the performance of the classifier using Confusion Matrix

In [181]:
# Predicting the Test set results
best_model = grid_search.best_estimator_
Y_pred_label = best_model.predict(X_test_scaled)
Y_pred = list(encoder.inverse_transform(Y_pred_label))

# Making the Confusion Matrix
#print(pd.crosstab(Y_test_label, Y_pred_label, rownames=['Actual Activity'], colnames=['Predicted Activity']))
print(confusion_matrix(Y_test_label,Y_pred_label))
print("\n")
print(classification_report(Y_test_label,Y_pred_label))

print("Training set score for RF: %f" % best_model.score(X_train_scaled , Y_train_label))
print("Testing  set score for RF: %f" % best_model.score(X_test_scaled  , Y_test_label ))



[[537   0   0   0   0   0]
 [  0 444  47   0   0   0]
 [  0  45 487   0   0   0]
 [  0   0   0 482   8   6]
 [  0   0   0  23 356  41]
 [  0   0   0  32   7 432]]


             precision    recall  f1-score   support

          0       1.00      1.00      1.00       537
          1       0.91      0.90      0.91       491
          2       0.91      0.92      0.91       532
          3       0.90      0.97      0.93       496
          4       0.96      0.85      0.90       420
          5       0.90      0.92      0.91       471

avg / total       0.93      0.93      0.93      2947

Training set score for RF: 1.000000
Testing  set score for RF: 0.929080


200